In [3]:
# 1.pandas序列
import numpy as np
import pandas as pd
s_data = pd.Series([1,3,5,np.NaN,9,11])
print (s_data)#pandas中生产序列的函数，类似于我们平时说的数组



0     1.0
1     3.0
2     5.0
3     NaN
4     9.0
5    11.0
dtype: float64


In [5]:
# 2.pandas数据结构DataFrame
import numpy as np  
import pandas as pd  
  
#以20170220为基点向后生产时间点  
dates = pd.date_range('20170220',periods=6)  
#DataFrame生成函数，行索引为时间点，列索引为ABCD  
data = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))  
print (data)  
print  
print (data.shape)  
print  
print (data.values)



                   A         B         C         D
2017-02-20 -1.079790  1.509608  1.586393  0.505632
2017-02-21  1.926485  0.349182 -0.743648  0.668754
2017-02-22 -1.500970  1.821580  0.106566 -1.819372
2017-02-23  0.763197 -0.384582 -0.133987 -0.853955
2017-02-24 -2.612796 -1.377007 -1.010935 -0.431912
2017-02-25  0.907587 -0.590964  0.419495 -1.599378
(6, 4)
[[-1.07979017  1.50960842  1.58639326  0.5056322 ]
 [ 1.926485    0.34918171 -0.74364767  0.66875392]
 [-1.50096999  1.82157953  0.10656587 -1.81937154]
 [ 0.76319719 -0.38458163 -0.13398717 -0.85395492]
 [-2.61279573 -1.37700723 -1.01093489 -0.43191222]
 [ 0.90758699 -0.59096437  0.41949452 -1.59937821]]


In [9]:
# 3.DataFrame的一些操作(1)
import numpy as np  
import pandas as pd  
      
#设计一个字典  
d_data = {'A':1,'B':pd.Timestamp('20170220'),'C':range(4),'D':np.arange(4)}  
print (d_data)
#使用字典生成一个DataFrame  
df_data = pd.DataFrame(d_data)  
print (df_data)
#DataFrame中每一列的类型  
print (df_data.dtypes)
#打印A列  
print (df_data.A)
#打印B列  
print (df_data.B)
#B列的类型  
print (type(df_data.B))


{'A': 1, 'B': Timestamp('2017-02-20 00:00:00'), 'C': range(0, 4), 'D': array([0, 1, 2, 3])}
   A          B  C  D
0  1 2017-02-20  0  0
1  1 2017-02-20  1  1
2  1 2017-02-20  2  2
3  1 2017-02-20  3  3
A             int64
B    datetime64[ns]
C             int32
D             int32
dtype: object
0    1
1    1
2    1
3    1
Name: A, dtype: int64
0   2017-02-20
1   2017-02-20
2   2017-02-20
3   2017-02-20
Name: B, dtype: datetime64[ns]
<class 'pandas.core.series.Series'>


In [12]:
# 4.DataFrame的一些操作(2)
import numpy as np  
import pandas as pd  
      
dates = pd.date_range('20170220',periods=6)  
data = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))  
print (data)  
print  
#输出DataFrame头部数据，默认为前5行  
print (data.head())  
#输出输出DataFrame第一行数据  
print (data.head(1))  
#输出DataFrame尾部数据，默认为后5行  
print (data.tail())  
#输出输出DataFrame最后一行数据  
print (data.tail(1))  
#输出行索引  
print (data.index)  
#输出列索引  
print (data.columns)  
#输出DataFrame数据值  
print (data.values)  
#输出DataFrame详细信息  
print (data.describe())  

                   A         B         C         D
2017-02-20 -0.358807  0.911403 -2.576704 -0.492043
2017-02-21  0.441321  0.565619 -0.919505 -0.037421
2017-02-22 -0.874804  0.415806  1.888624  0.262656
2017-02-23 -0.317713  2.208390 -0.980897 -0.781798
2017-02-24 -0.206496 -0.284715  1.474429 -0.394460
2017-02-25  0.364127 -1.256555 -0.057360  0.978507
                   A         B         C         D
2017-02-20 -0.358807  0.911403 -2.576704 -0.492043
2017-02-21  0.441321  0.565619 -0.919505 -0.037421
2017-02-22 -0.874804  0.415806  1.888624  0.262656
2017-02-23 -0.317713  2.208390 -0.980897 -0.781798
2017-02-24 -0.206496 -0.284715  1.474429 -0.394460
                   A         B         C         D
2017-02-20 -0.358807  0.911403 -2.576704 -0.492043
                   A         B         C         D
2017-02-21  0.441321  0.565619 -0.919505 -0.037421
2017-02-22 -0.874804  0.415806  1.888624  0.262656
2017-02-23 -0.317713  2.208390 -0.980897 -0.781798
2017-02-24 -0.206496 -0.284715 

In [16]:
# DataFrame的一些操作(3)
import numpy as np
import pandas as pd

dates = pd.date_range('20170220',periods=6)
data = pd.DataFrame(np.random.randn(6,4),index = dates,columns=list('ABCD'))
print (data)
#装置
print (data.T)
print (data.shape)
print (data.T.shape)
print (data.sort_index(axis = 1))
print (data.sort_index(axis = 1,ascending=False))
#将行索引排序，降序排列  
print (data.sort_index(axis = 0,ascending=False))
#按照A列的值进行升序排列  
print (data.sort_values(by='A')) 




                   A         B         C         D
2017-02-20 -3.501748  0.504383 -0.854935  0.386018
2017-02-21  1.031344 -1.691022 -0.300313 -1.377663
2017-02-22 -1.178832  1.180068 -1.533384 -0.234958
2017-02-23  0.555403 -0.597910  0.653298 -1.166531
2017-02-24  0.590857 -0.609650  0.110739 -0.736260
2017-02-25 -0.260893 -0.519667 -1.187638  0.985038
   2017-02-20  2017-02-21  2017-02-22  2017-02-23  2017-02-24  2017-02-25
A   -3.501748    1.031344   -1.178832    0.555403    0.590857   -0.260893
B    0.504383   -1.691022    1.180068   -0.597910   -0.609650   -0.519667
C   -0.854935   -0.300313   -1.533384    0.653298    0.110739   -1.187638
D    0.386018   -1.377663   -0.234958   -1.166531   -0.736260    0.985038
(6, 4)
(4, 6)
                   A         B         C         D
2017-02-20 -3.501748  0.504383 -0.854935  0.386018
2017-02-21  1.031344 -1.691022 -0.300313 -1.377663
2017-02-22 -1.178832  1.180068 -1.533384 -0.234958
2017-02-23  0.555403 -0.597910  0.653298 -1.166531
2017

In [29]:
import numpy as np  
import pandas as pd  
      
dates = pd.date_range('20170220',periods=6)  
data = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))  
print (data)

#输出A列  
print (data.A)  
#输出A列  
print (data['A'])  
#输出3,4行  
print (data[2:4])  
#输出3，4行  
print (data['20170222':'20170223'])  
#输出3,4行  
print (data.loc['20170222':'20170223'])  
#输出3,4行  
print (data.iloc[2:4])  
# 输出B,C两列  
print (data.loc[:,['B','C']])  
#输出A列中大于0的行   
       
print (data[data.A > 0])  
#输出大于0的数据，小于等于0的用NaN补位  
print (data[data > 0])  
#拷贝data  
data2 = data.copy()  
print (data2)  
tag = ['a'] * 2 + ['b'] * 2 + ['c'] * 2  
#在data2中增加TAG列用tag赋值  
data2['TAG'] = tag  
print (data2) 
#打印TAG列中为a,c的行  
print (data2[data2.TAG.isin(['a','c'])]) 
print (data2[data2.TAG.isin(['b','d'])])
#将第一行第一列元素赋值为100 
data.iat[0,0] = 100
print (data)
#将A列元素用range(6)赋值
data.A = range(6)
print (data)
#将B列元素赋值为200
data.B = 200
#将3,4列元素赋值为1000
data.iloc[:,2:4] = 1000
print (data)

                   A         B         C         D
2017-02-20 -0.088990 -0.485556  0.147372  1.219924
2017-02-21 -1.361804  0.251366  0.079771 -0.157715
2017-02-22 -0.715405 -0.506121 -0.681256 -0.943519
2017-02-23 -0.097486 -0.580209  0.701733 -0.278409
2017-02-24  0.258062  0.790111 -0.530900 -0.403164
2017-02-25  1.900875 -0.761749 -2.169284  0.696049
2017-02-20   -0.088990
2017-02-21   -1.361804
2017-02-22   -0.715405
2017-02-23   -0.097486
2017-02-24    0.258062
2017-02-25    1.900875
Freq: D, Name: A, dtype: float64
2017-02-20   -0.088990
2017-02-21   -1.361804
2017-02-22   -0.715405
2017-02-23   -0.097486
2017-02-24    0.258062
2017-02-25    1.900875
Freq: D, Name: A, dtype: float64
                   A         B         C         D
2017-02-22 -0.715405 -0.506121 -0.681256 -0.943519
2017-02-23 -0.097486 -0.580209  0.701733 -0.278409
                   A         B         C         D
2017-02-22 -0.715405 -0.506121 -0.681256 -0.943519
2017-02-23 -0.097486 -0.580209  0.701733 -0.27

In [35]:
import numpy as np  
import pandas as pd  
      
dates = pd.date_range('20170220',periods = 6)  
df = pd.DataFrame(np.random.randn(6,4) , index = dates , columns = list('ABCD'))  
print (df)  
#重定义索引，并添加E列  
dfl = df.reindex(index = dates[0:4],columns = list(df.columns)+['E'])  
print (dfl)  
#将E列中的2,3行赋值为2  
dfl.loc[dates[1:3],'E'] = 2  
print (dfl)  
#去掉存在NaN元素的行  
print (dfl.dropna())
a = dfl.dropna()
print (a)
print (dfl)
#将NaN元素赋值为5  
print (dfl.fillna(5))
#判断每个元素是否为NaN  
print (pd.isnull(dfl))  
#求列平均值  
print (dfl.mean())  
#对每列进行累加  
print (dfl.cumsum())  

                   A         B         C         D
2017-02-20  2.267136 -0.547718 -0.382923 -0.021666
2017-02-21  0.917288  0.025866 -0.481914  0.382113
2017-02-22 -1.059643 -1.734006  2.026638  1.028106
2017-02-23 -0.040138  1.382292 -1.141825  0.019570
2017-02-24 -0.818752  1.467518  0.207342 -0.308680
2017-02-25  0.461474  0.492682 -1.437031  0.156355
                   A         B         C         D   E
2017-02-20  2.267136 -0.547718 -0.382923 -0.021666 NaN
2017-02-21  0.917288  0.025866 -0.481914  0.382113 NaN
2017-02-22 -1.059643 -1.734006  2.026638  1.028106 NaN
2017-02-23 -0.040138  1.382292 -1.141825  0.019570 NaN
                   A         B         C         D    E
2017-02-20  2.267136 -0.547718 -0.382923 -0.021666  NaN
2017-02-21  0.917288  0.025866 -0.481914  0.382113  2.0
2017-02-22 -1.059643 -1.734006  2.026638  1.028106  2.0
2017-02-23 -0.040138  1.382292 -1.141825  0.019570  NaN
                   A         B         C         D    E
2017-02-21  0.917288  0.025866 -

In [55]:
import numpy as np  
import pandas as pd  
dates = pd.date_range('20170220',periods = 6)  
df = pd.DataFrame(np.random.randn(6,4) , index = dates , columns = list('ABCD'))
dfl = df.reindex(index = dates[0:4],columns = list(df.columns) + ['E'])
print (dfl)
#针对行求平均值 
print (dfl.mean(axis = 1))
#生成序列并向右平移两位 
s = pd.Series([1,3,5,np.nan,6,8],index = dates).shift(2)
print (s)
#df与s做减法运算  
print (df.sub(s,axis = 0))
print (df.sub(s,axis = 'index'))
#每列进行累加运算 
print (df.apply(np.cumsum))
#每列的最大值减去最小值 
print (df.apply(lambda x:x.max() - x.min()))


                   A         B         C         D   E
2017-02-20 -1.623918  0.457963 -0.247858 -0.633367 NaN
2017-02-21  0.222180  0.468179 -0.132461  1.462409 NaN
2017-02-22  0.210056 -2.154606  1.801428 -0.309317 NaN
2017-02-23  0.148093 -1.959656 -0.768260 -2.100926 NaN
2017-02-20   -0.511795
2017-02-21    0.505077
2017-02-22   -0.113110
2017-02-23   -1.170187
Freq: D, dtype: float64
2017-02-20    NaN
2017-02-21    NaN
2017-02-22    1.0
2017-02-23    3.0
2017-02-24    5.0
2017-02-25    NaN
Freq: D, dtype: float64
                   A         B         C         D
2017-02-20       NaN       NaN       NaN       NaN
2017-02-21       NaN       NaN       NaN       NaN
2017-02-22 -0.789944 -3.154606  0.801428 -1.309317
2017-02-23 -2.851907 -4.959656 -3.768260 -5.100926
2017-02-24 -5.024171 -4.465741 -4.539009 -4.370708
2017-02-25       NaN       NaN       NaN       NaN
                   A         B         C         D
2017-02-20       NaN       NaN       NaN       NaN
2017-02-21       N

In [57]:
import numpy as np  
import pandas as pd  
dates = pd.date_range('20170220',periods = 6)  
df = pd.DataFrame(np.random.randn(6,4) , index = dates , columns = list('ABCD'))  

#定义一个函数,求每一列的和
def _sum(x):  
    print(type(x))  
    return x.sum()  
#apply函数可以接受一个函数作为参数  
print (df.apply(_sum))  
s = pd.Series(np.random.randint(10,20,size = 15))  
print (s)  
#统计序列中每个元素出现的次数  
print (s.value_counts())  
#返回出现次数最多的元素  
print (s.mode())  

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
A   -0.161992
B    1.586722
C    1.309517
D    0.369873
dtype: float64
0     13
1     13
2     12
3     13
4     15
5     19
6     12
7     16
8     12
9     13
10    14
11    11
12    13
13    10
14    11
dtype: int32
13    5
12    3
11    2
15    1
14    1
10    1
19    1
16    1
dtype: int64
0    13
dtype: int32
